language: bash

before_script:
    - curl -L "http://downloads.sourceforge.net/shunit2/shunit2-2.0.3.tgz" | tar zx

script:
    - (cd base/test ; bash gen_test.sh && bash collect_test.sh)
    - (cd bind9/test ; bash gen_test.sh)
