apiVersion: v1
kind: PersistentVolume
metadata:
  labels:
    app: fluentd
    pkg: fluentd
  name: fluentd-sources
  namespace: default
spec:
  accessModes:
  - ReadOnlyMany
  capacity:
    storage: 500Mi
  hostPath:
    path: /var/log/containers 
---
apiVersion: v1
kind: PersistentVolume
metadata:
  labels:
    app: fluentd
    pkg: fluentd
  name: fluentd-logs
  namespace: default
spec:
  accessModes:
  - ReadWriteMany
  capacity:
    storage: 500Mi
  hostPath:
    path: /var/log/fluentd
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    pkg: fluentd
  name: fluentd-sources-claim
  namespace: default
spec:
  accessModes:
  - ReadOnlyMany
  resources:
    requests:
      storage: 50Mi
  volumeName: fluentd-sources
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    pkg: fluentd
  name: fluentd-logs-claim
  namespace: default
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 500Mi
  volumeName: fluentd-logs
