apiVersion: v1
kind: Service
metadata:
  name: syslog
spec:
  externalIPs:
  - 192.168.2.254
  ports:
  - name: fluent 
    port: 24224
    protocol: TCP
    targetPort: 24224
  - name: syslog
    port: 514
    protocol: UDP
    targetPort: 5140
  selector:
    app: fluentd-fwd
  sessionAffinity: None
  type: ClusterIP
