apiVersion: v1
kind: PersistentVolume
metadata:
  labels:
    app: syslog
    pkg: rsyslog
  name: rsyslog-sources
  namespace: default
spec:
  accessModes:
  - ReadOnlyMany
  capacity:
    storage: 500Mi
  hostPath:
    path: /var/log/containers 
---
apiVersion: v1
kind: PersistentVolume
metadata:
  labels:
    app: syslog
    pkg: rsyslog
  name: rsyslog-logs
  namespace: default
spec:
  accessModes:
  - ReadWriteMany
  capacity:
    storage: 500Mi
  hostPath:
    path: /var/log/rsyslog
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    pkg: rsyslog
  name: rsyslog-sources-claim
  namespace: default
spec:
  accessModes:
  - ReadOnlyMany
  resources:
    requests:
      storage: 50Mi
  volumeName: rsyslog-sources
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    pkg: rsyslog
  name: rsyslog-logs-claim
  namespace: default
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 500Mi
  volumeName: rsyslog-logs
