apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: rsyslog-fwd
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: syslog-fwd
        pkg: rsyslog-fwd
    spec:
      containers:
      - env:
        - name: forward_to
          value: tcp:syslog-sink
        - name: with_tcp
          value : "1"
        - name: xxrsyslogd_options
          value: "-d"
        image: aschults/bluebox_rsyslog:latest
        imagePullPolicy: Always
        name: rsyslog-fwd
        ports:
        - containerPort: 10514
          name: syslog-tcp
          protocol: TCP
        - containerPort: 514
          name: syslog
          protocol: UDP
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
