apiVersion: v1
kind: Service
metadata:
  name: syslog-sink
spec:
  ports:
  - name: syslog-tcp
    port: 10514
    protocol: TCP
    targetPort: 10514
  selector:
    app: syslog-sink
  sessionAffinity: None
  type: ClusterIP
